[project]
name = "fishr"
version = "0.0.1"
description = "A python library for free LLMs & usable in your python projects. (Grok, Sonnet, GPT)"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
    { name = "fuhnut" }
]
keywords = [
    "llm",
    "ai",
    "grok",
    "gpt",
    "gemini",
    "sonnet",
    "chat",
    "completions",
    "free",
    "no-auth",
    "gpt4free",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "uvloop>=0.22.1 ; sys_platform != 'win32'",
    "primp",
    "msgspec",
    "static-ffmpeg",
]

[project.urls]
Homepage = "https://github.com/breedservices/fishr"
Repository = "https://github.com/breedservices/fishr"
Issues = "https://github.com/breedservices/fishr/issues"

[project.scripts]
fishr = "fishr.__main__:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
