[project]
name = "fishr"
version = "0.0.1"
description = "A python library for free LLMs & usable in your python projects. (Grok, Sonnet, GPT)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "uvloop>=0.22.1 ; sys_platform != 'win32'",
    "primp",
    "msgspec",
]

[project.scripts]
fishr = "fishr.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
